import { Order, Expense, BatchTanda, ProductCatalogItem } from './types';

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-089',
    orderNumber: '#089',
    customerName: 'Martín Rodríguez',
    phone: '+54 9 11 4521-8890',
    isDelivery: true,
    address: 'Av. Corrientes 3421, Piso 4B',
    motoAssignee: 'Moto #2',
    deliveryEstimatedTime: '',
    items: [
      { id: 'i1', name: 'Saladas (6 Carne suave, 6 Jamón y queso)', quantity: 12, unitLabel: '1d', unitPrice: 10800, category: 'saladas' },
      { id: 'i2', name: 'Árabes (sfijas al limón)', quantity: 6, unitLabel: '½d', unitPrice: 5700, category: 'arabes' },
      { id: 'i3', name: 'Coca-Cola 1.5L descartable', quantity: 1, unitLabel: '1x', unitPrice: 2200, category: 'bebidas' },
    ],
    itemsSummary: [
      'Saladas (6 Carne suave, 6 Jamón y queso)',
      'Árabes (sfijas al limón)',
      'Coca-Cola 1.5L descartable',
    ],
    total: 14200,
    paymentStatus: 'PAGADO',
    paymentMethod: 'Transferencia',
    paymentDetail: 'Transferencia MP comprobada',
    status: 'en_camino',
    isWhatsApp: true,
    createdAt: '20:15',
  },
  {
    id: 'ord-090',
    orderNumber: '#090',
    customerName: 'Lucía Fernández',
    phone: '+54 9 11 6789-1234',
    isDelivery: true,
    address: 'Belgrano 145 (Timbre Blanco)',
    motoAssignee: '',
    deliveryEstimatedTime: 'Sale 21:15',
    items: [
      { id: 'i4', name: '24 Unidades (12 Dulce membrillo, 12 Carne picante)', quantity: 24, unitLabel: '2d', unitPrice: 21600, category: 'saladas' },
      { id: 'i5', name: 'Sprite Regular 1.5L', quantity: 2, unitLabel: '2x', unitPrice: 4400, category: 'bebidas' },
    ],
    itemsSummary: [
      '24 Unidades (12 Dulce membrillo, 12 Carne picante)',
      'Sprite Regular 1.5L',
    ],
    total: 22800,
    paymentStatus: 'COBRAR_EFECTIVO',
    paymentMethod: 'Efectivo',
    paymentDetail: 'Prepara cambio con $30.000',
    status: 'en_horno',
    isWhatsApp: true,
    createdAt: '20:30',
  },
  {
    id: 'ord-091',
    orderNumber: '#091',
    customerName: 'Gastón Silva',
    phone: '',
    isDelivery: false,
    pickupTime: 'Pasa a retirar en 15m',
    items: [
      { id: 'i6', name: '6x Árabes (sfijas abiertas con limón)', quantity: 6, unitLabel: '½d', unitPrice: 4500, category: 'arabes' },
    ],
    itemsSummary: [
      '6x Árabes (sfijas abiertas con limón)',
    ],
    total: 4500,
    paymentStatus: 'COBRAR_EFECTIVO',
    paymentMethod: 'Efectivo',
    paymentDetail: 'Cobro en mostrador',
    status: 'pendiente_cocina',
    isWhatsApp: false,
    createdAt: '20:42',
  },
  {
    id: 'ord-092',
    orderNumber: '#092',
    customerName: 'Mariana Costa',
    phone: '+54 9 11 3499-1200',
    isDelivery: true,
    address: 'Amenábar 2180, Dpto 3',
    motoAssignee: 'Moto #1',
    deliveryEstimatedTime: 'Sale 21:30',
    items: [
      { id: 'i7', name: '12x Saladas surtidas (Carne Picante, Pollo)', quantity: 12, unitLabel: '1d', unitPrice: 10800, category: 'saladas' },
      { id: 'i8', name: '6x Dulces de Batata', quantity: 6, unitLabel: '½d', unitPrice: 5100, category: 'dulces' },
    ],
    itemsSummary: [
      '12x Saladas surtidas (Carne Picante, Pollo)',
      '6x Dulces de Batata',
    ],
    total: 18900,
    paymentStatus: 'PAGADO',
    paymentMethod: 'Mercado Pago',
    paymentDetail: 'Pago verificado QR',
    status: 'en_horno',
    isWhatsApp: true,
    createdAt: '20:50',
  },
  {
    id: 'ord-093',
    orderNumber: '#093',
    customerName: 'Rodrigo Benítez',
    phone: '+54 9 11 8721-0023',
    isDelivery: true,
    address: 'Av. Triunvirato 4120',
    motoAssignee: 'Moto #2',
    deliveryEstimatedTime: 'En viaje',
    items: [
      { id: 'i9', name: '12x Carne Suave criolla', quantity: 12, unitLabel: '1d', unitPrice: 10800, category: 'saladas' },
    ],
    itemsSummary: [
      '12x Carne Suave criolla',
    ],
    total: 10800,
    paymentStatus: 'PAGADO',
    paymentMethod: 'Transferencia',
    paymentDetail: 'Transferencia MP comprobada',
    status: 'en_camino',
    isWhatsApp: true,
    createdAt: '20:25',
  },
  {
    id: 'ord-094',
    orderNumber: '#094',
    customerName: 'Camila Ruiz',
    phone: '+54 9 11 5566-7788',
    isDelivery: true,
    address: 'Juramento 1945, 7A',
    items: [
      { id: 'i10', name: '12x Verdura & Queso Reggianito', quantity: 12, unitLabel: '1d', unitPrice: 10800, category: 'saladas' },
      { id: 'i11', name: '1x Cerveza Artesanal Golden', quantity: 1, unitLabel: '1x', unitPrice: 2500, category: 'bebidas' },
    ],
    itemsSummary: [
      '12x Verdura & Queso Reggianito',
      '1x Cerveza Artesanal Golden',
    ],
    total: 13300,
    paymentStatus: 'COBRAR_EFECTIVO',
    paymentMethod: 'Efectivo',
    paymentDetail: 'Abonará con cambio justo',
    status: 'pendiente_cocina',
    isWhatsApp: true,
    createdAt: '20:55',
  },
  {
    id: 'ord-095',
    orderNumber: '#095',
    customerName: 'Lucas Méndez',
    phone: '',
    isDelivery: false,
    pickupTime: 'Pasa a retirar en 10m',
    items: [
      { id: 'i12', name: '6x Jamón & Mozzarella', quantity: 6, unitLabel: '½d', unitPrice: 5400, category: 'saladas' },
      { id: 'i13', name: '1x Coca-Cola 1.5L', quantity: 1, unitLabel: '1x', unitPrice: 2200, category: 'bebidas' },
    ],
    itemsSummary: [
      '6x Jamón & Mozzarella',
      '1x Coca-Cola 1.5L',
    ],
    total: 7600,
    paymentStatus: 'COBRAR_EFECTIVO',
    paymentMethod: 'Efectivo',
    paymentDetail: 'Cobro en mostrador',
    status: 'en_horno',
    isWhatsApp: false,
    createdAt: '21:00',
  },
  {
    id: 'ord-096',
    orderNumber: '#088',
    customerName: 'Valeria Paz',
    phone: '+54 9 11 9988-1122',
    isDelivery: true,
    address: 'Moldes 1430',
    motoAssignee: 'Moto #1',
    items: [
      { id: 'i14', name: '12x Saladas Surtidas', quantity: 12, unitLabel: '1d', unitPrice: 10800, category: 'saladas' },
    ],
    itemsSummary: ['12x Saladas Surtidas'],
    total: 10800,
    paymentStatus: 'PAGADO',
    paymentMethod: 'Transferencia',
    paymentDetail: 'Transferencia acreditada',
    status: 'entregado',
    isWhatsApp: true,
    createdAt: '19:40',
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    concept: 'Harina 0000 x 25kg (Insumo)',
    amount: 14000,
    method: 'Efectivo',
    time: '18:20 hs',
    category: 'bakery_dining',
  },
  {
    id: 'exp-2',
    concept: 'Carne picada especial 10kg',
    amount: 24500,
    method: 'Transferencia',
    time: '16:15 hs',
    category: 'restaurant',
  },
  {
    id: 'exp-3',
    concept: 'Cajas delivery x 100u (Packaging)',
    amount: 6700,
    method: 'Efectivo',
    time: '15:00 hs',
    category: 'package_2',
  },
];

export const INITIAL_TANDAS: BatchTanda[] = [
  {
    id: 't-4',
    number: 4,
    units: 80,
    time: '20:45 hs',
    cook: 'Marcos V.',
    oven: 'Horno 1',
    status: 'Listo',
  },
  {
    id: 't-3',
    number: 3,
    units: 120,
    time: '19:30 hs',
    cook: 'Sofia R.',
    oven: 'Horno 2',
    status: 'Despachado',
  },
  {
    id: 't-2',
    number: 2,
    units: 100,
    time: '18:15 hs',
    cook: 'Marcos V.',
    oven: 'Horno 1',
    status: 'Despachado',
  },
  {
    id: 't-1',
    number: 1,
    units: 60,
    time: '17:00 hs',
    cook: 'Sofia R.',
    oven: 'Horno 1',
    status: 'Despachado',
  },
];

export const PRODUCT_CATALOG: ProductCatalogItem[] = [
  // Saladas Tradicionales
  {
    id: 'prod-carne-suave',
    name: 'Carne Suave',
    description: 'Carne cortada a cuchillo, huevo y cebolla de verdeo',
    category: 'saladas',
    price: 900,
    tag: 'En carta',
  },
  {
    id: 'prod-carne-picante',
    name: 'Carne Picante',
    description: 'Ají molido de Cachi, comino y verdeo',
    category: 'saladas',
    price: 900,
    tag: 'En carta',
  },
  {
    id: 'prod-jamon-queso',
    name: 'Jamón y Queso',
    description: 'Mozzarella fundente y jamón cocido seleccionado',
    category: 'saladas',
    price: 900,
  },
  {
    id: 'prod-pollo',
    name: 'Pollo al Horno',
    description: 'Pechuga desmenuzada, puerro y pimientos asados',
    category: 'saladas',
    price: 900,
  },
  {
    id: 'prod-verdura',
    name: 'Verdura & Parmesano',
    description: 'Espinaca fresca, salsa blanca y queso reggianito',
    category: 'saladas',
    price: 900,
  },
  // Especialidades Árabes
  {
    id: 'prod-sfijas',
    name: 'Sfijas al Limón',
    description: 'Carne macerada en limón natural, tomate, 7 especias orientales',
    category: 'arabes',
    price: 950,
    badge: 'Tradicional',
  },
  // Dulces de Horno
  {
    id: 'prod-membrillo',
    name: 'Membrillo & Nuez',
    description: 'Dulce de membrillo casero con nueces tostadas',
    category: 'dulces',
    price: 850,
    tag: 'En carta',
  },
  {
    id: 'prod-batata',
    name: 'Batata & Canela',
    description: 'Dulce de batata con un toque de vainilla y canela',
    category: 'dulces',
    price: 850,
  },
  // Bebidas y Gaseosas
  {
    id: 'prod-coca',
    name: 'Coca-Cola 1.5L',
    description: 'Línea descartable fría',
    category: 'bebidas',
    price: 2200,
  },
  {
    id: 'prod-sprite',
    name: 'Sprite 1.5L',
    description: 'Línea descartable fría',
    category: 'bebidas',
    price: 2200,
  },
  {
    id: 'prod-agua',
    name: 'Agua Mineral 500ml',
    description: 'Con o sin gas',
    category: 'bebidas',
    price: 1200,
  },
  {
    id: 'prod-cerveza',
    name: 'Cerveza Artesanal',
    description: 'Golden Ale 500ml lata fría',
    category: 'bebidas',
    price: 2500,
  },
];

export const BRAND_IMAGES = {
  logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqbfbMvkC0s3rIbZreFZYown4LYk_JV6b9zheMxMnEVxSqBexTvHY1SYlnZB7W5p5vZPnjXD1Rs_MgXRXFSR0Jaf__rnuFP6iTnhz6M1HV5u8cUwqy8U36no0RgCuaequHKv3wB6JkcvLYScaofNVc2zGCxclVMbec-jJ2dVZ5uxXb9SJdn41xFAPENeOcEQSpXZJ9PUhzgtX1js5aWaPfYn0uIM7RBtkecrkhYVn0318CiFnKGWai',
  saladas: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA88CIyVFXs697x5ggZ1P5Ryri1jEU5lQh8bUoKN-Ti0r-fnpiMY1racG2ML6Hq08f1FEAiLQ73w5U1mu9ig0cqnOx8i4IbunCI29yRxPo2V-zQCB_OPBWEu5loMLdkOXwu1FCqIo0IPPxtMSnog5-pnQ7KhlGVebp6RQ0B_zSmQI9XuiPj4a0rSJSVy7m1tWCv5BaPIEfp2TAlr6Y8lPJQ83c_gJQVEMmsNJM5XaPK_q7MIAeSmtuG',
  dulces: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYJ4WqilRMHAbMBfFDD5E4Ac0Wc7KF4X928auxa_CEjN3_GhkwT4RBnv6SL2mTojKlUyKWcouZjFbBFh01nnp1h-g87cmAwlF9sEaVyxFv_PQXt4KFdKQVKcbl8YUfopBPtRU_1xjv24Kn-VrL_zRDZq4omvTGY3OsSOe3yZUyiR6YApRvOGV5cTbWT7oR-AxEuVr2MIygUOHQC2FhwP2GUuplwW8SldHueNUVVnaGEwdMiRPrRQzU',
  arabes: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXPZX2TVr5XXkhSshbdzJwnkCol5wd05QIIqUuYEXl5uI0uhL8C37Pwj6uga5QaVQjU_EiEgGs75MJhsUYORc5prGAD7znuxE-d2BgA80rb1NymunHfwm_f6MPuk5Pj_3hqXQVQOkAzISbj_CcRxmG2bR7omg55YND4QJ03hNryaqM-x_IgMlgW_KxFP8fV1P1KojJDnm95Ej6VTSaNy0xqqgE-DfKYKwVYw9ffatHzNfwm7yGJ_zT',
};
